spring:
  profiles:
    group:
      local: local,common
      ci: ci,common

---

spring:
  config:
    activate:
      on-profile: common

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwerqwer

  jpa:
    show-sql: true
    database: mysql
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

---

spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: ci

  jpa:
    hibernate:
      ddl-auto: validate
